site_name: Denis Mulyalin Blog
site_author: Denis Mulyalin
site_description: Blog to share my thoughts, news and ideas 
site_url: https://dmulyalin.github.io/

theme:
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - toc.integrate
  icon:
    repo: fontawesome/brands/github-alt
  name: material
  font:
    text: Source Serif Pro
  icon:
    repo: fontawesome/brands/github-alt
  palette: 
    # Palette toggle for light mode
    - scheme: default
      accent: teal
      primary: grey
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      accent: teal
      primary: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
plugins:
- search

markdown_extensions:
- admonition
- pymdownx.details
- attr_list
- md_in_html
- pymdownx.superfences
- toc:
    permalink: "#"
    baselevel: 2
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
      
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/dmulyalin
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/DMulyalin

nav:
- About: index.md
- Blog:
  - posts.md
- Posts:
  - 2022-08-21-5-efficient-ways-to-collect-show-commands-output-from-network-devices.md
  