[tool.poetry]
name = "dmulyalin.github.io"
version = "0.1.0"
description = ""
authors = ["Denis <d.mulyalin@gmail.com>"]
license = "MIT"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
mkdocs = { version = "*", optional = false, markers = "python_version >= '3.7'" }
mkdocs-material = { version = "*", optional = false, markers = "python_version >= '3.7'" }
mkdocs-material-extensions = { version = "*", optional = false, markers = "python_version >= '3.7'" }
mkdocstrings = { version = "*", optional = false, markers = "python_version >= '3.7'", extras = ["python"] } 
pygments = { version = "*", optional = false, markers = "python_version >= '3.7'" }
pymdown-extensions = { version = "*", optional = false, markers = "python_version >= '3.7'" }

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
